# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a424cf518b039b7b865bde45c25e82a2b1fcf8ec97135181f43ffd9ba093816e9b910ea8e8dbc3b851d12c138be2886f9c32a29e39952401cea093f0e521e93f

test:
  secret_key_base: 73cac4793a231554285adfba66aae8ffcd62ca1cd777aeab52c0a0cd22f528969ad692f77880626ad51eb9df4422ddf11b1e548bd0f763804876ccd9c9234373

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

